# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_teacher_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='company',
        ),
    ]
