# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
