# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('cellphone_number', models.CharField(max_length=11, verbose_name='手机号')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('avatar', models.ImageField(default='static/imgs/default.png', upload_to='static/imgs/%Y/%m', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default=None, max_length=6, verbose_name='性别')),
            ],
        ),
    ]
