# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180101_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=50, verbose_name='视频名'),
        ),
    ]
