# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20180101_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresouce',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
    ]
